Repository 4team-final/server, pull requests merged in 2022-06, with the labels that each got.

#3 refactor: 패키지 리팩토링 #2
  src/main/java/com/douzone/server/admin/controller/RoomController.java
  src/main/java/com/douzone/server/admin/controller/VehicleController.java
  src/main/java/com/douzone/server/admin/domain/room/Room.java
  src/main/java/com/douzone/server/admin/domain/room/RoomRepository.java
  src/main/java/com/douzone/server/admin/domain/vehicle/Vehicle.java
  src/main/java/com/douzone/server/admin/domain/vehicle/VehicleRepository.java
  src/main/java/com/douzone/server/admin/dto/room/RoomReqDTO.java
  src/main/java/com/douzone/server/admin/dto/vehicle/VehicleReqDTO.java
  src/main/java/com/douzone/server/admin/exception/AdminNotFoundException.java
  src/main/java/com/douzone/server/admin/service/RoomService.java
  src/main/java/com/douzone/server/admin/service/VehicleService.java
  src/main/java/com/douzone/server/controller/board/BoardController.java
  src/main/java/com/douzone/server/controller/testController.java
  src/main/java/com/douzone/server/controller/user/UserController.java
  src/main/java/com/douzone/server/domain/entity/BoardEntity.java
  src/main/java/com/douzone/server/domain/entity/TestEntity.java
  src/main/java/com/douzone/server/domain/entity/UserEntity.java
  src/main/java/com/douzone/server/domain/repository/BoardRepository.java
  src/main/java/com/douzone/server/domain/repository/TestRepository.java
  src/main/java/com/douzone/server/domain/repository/UserRepository.java
  src/main/java/com/douzone/server/dto/TestDto.java
  src/main/java/com/douzone/server/dto/board/BoardReqDto.java
  src/main/java/com/douzone/server/dto/common/Response.java
  src/main/java/com/douzone/server/dto/user/UserReqDto.java
  src/main/java/com/douzone/server/employee/controller/RoomController.java
  src/main/java/com/douzone/server/employee/controller/VehicleController.java
  src/main/java/com/douzone/server/employee/domain/room/Room.java
  src/main/java/com/douzone/server/employee/domain/room/RoomRepository.java
  src/main/java/com/douzone/server/employee/domain/vehicle/Vehicle.java
  src/main/java/com/douzone/server/employee/domain/vehicle/VehicleRepository.java
  src/main/java/com/douzone/server/employee/dto/room/RoomReqDTO.java
  src/main/java/com/douzone/server/employee/dto/vehicle/VehicleReqDTO.java
  src/main/java/com/douzone/server/employee/exception/EmployeeNotFoundException.java
  src/main/java/com/douzone/server/employee/service/RoomService.java
  src/main/java/com/douzone/server/employee/service/VehicleService.java
  src/main/java/com/douzone/server/exception/ExceptionInfo.java
  src/main/java/com/douzone/server/exception/board/BoardNotFoundException.java
  src/main/java/com/douzone/server/exception/user/UserNotFoundException.java
  src/main/java/com/douzone/server/service/TestService.java
  src/main/java/com/douzone/server/service/board/BoardService.java
  src/main/java/com/douzone/server/service/user/UserService.java
Labels: ✂ REFAC, 📜 TEST

#5 Test: 깃 pr 이슈 연결 테스트 #4
  src/main/java/com/douzone/server/test/Test.java
Labels: 📜 TEST

#7 feat:스프링 시큐리티, jjwt gradle추가 및 웹시큐리티 설정 파일 생성 #6
  .gitignore
  build.gradle
  src/main/java/com/douzone/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/douzone/server/config/security/WebSecurityConfig.java
  src/main/java/com/douzone/server/config/security/auth/PrincipalDetailService.java
  src/main/java/com/douzone/server/config/security/auth/PrincipalDetails.java
  src/main/java/com/douzone/server/config/security/filter/GlobalFilter.java
  src/main/java/com/douzone/server/config/security/filter/JwtTokenAuthorizationFilter.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationFilter.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationManager.java
  src/main/java/com/douzone/server/config/security/handler/DecodeEncodeHandler.java
  src/main/java/com/douzone/server/config/security/handler/ResponseHandler.java
  src/main/java/com/douzone/server/config/security/handler/UserLoginFailureHandler.java
  src/main/java/com/douzone/server/config/security/handler/UserLogoutHandler.java
  src/main/java/com/douzone/server/config/security/handler/UserLogoutSuccessHandler.java
  src/main/java/com/douzone/server/config/security/interceptor/InterceptorConfig.java
  src/main/java/com/douzone/server/config/security/interceptor/RoleInterceptor.java
  src/main/java/com/douzone/server/config/utils/BaseAtTime.java
  src/main/java/com/douzone/server/config/utils/Payload.java
  src/main/java/com/douzone/server/config/utils/ResponseDTO.java
  src/main/java/com/douzone/server/employee/domain/employee/Department.java
  src/main/java/com/douzone/server/employee/domain/employee/Employee.java
  src/main/java/com/douzone/server/employee/domain/employee/EmployeeRepository.java
  src/main/java/com/douzone/server/employee/domain/employee/Position.java
  src/main/java/com/douzone/server/employee/domain/employee/Team.java
  src/main/java/com/douzone/server/employee/domain/token/CommonTokenSet.java
  src/main/java/com/douzone/server/employee/domain/token/ReIssuanceTokenSet.java
  src/main/java/com/douzone/server/employee/domain/token/Token.java
  src/main/java/com/douzone/server/employee/domain/token/TokenRepository.java
  src/main/java/com/douzone/server/employee/dto/token/TokenResDTO.java
  src/main/java/com/douzone/server/test/Test.java
  src/main/resources/application.yml
Labels: 🙂 FEAT, 📜 TEST

#12 fix: 필터 환경변수 관리 설정 변경 #11
  src/main/java/com/douzone/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/douzone/server/config/security/WebSecurityConfig.java
  src/main/java/com/douzone/server/config/security/filter/GlobalFilter.java
  src/main/java/com/douzone/server/config/security/filter/JwtTokenAuthorizationFilter.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationFilter.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationManager.java
  src/main/java/com/douzone/server/employee/domain/token/CommonTokenSet.java
  src/main/java/com/douzone/server/employee/dto/token/CommonTokenDTO.java
  src/main/java/com/douzone/server/employee/dto/token/ReIssuanceTokenDTO.java
Labels: 🔨 FIX, 📜 TEST

#22 feat: 차량 create 기능 추가(+admin) #15
  src/main/java/com/douzone/server/controller/AdminController.java
  src/main/java/com/douzone/server/controller/VehicleController.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleReservationDTO.java
  src/main/java/com/douzone/server/repository/VehicleBookmarkRepository.java
  src/main/java/com/douzone/server/repository/VehicleReservationRepository.java
  src/main/java/com/douzone/server/service/AdminService.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🙂 FEAT

#28 feat : 회의실 예약현황 조회 2
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/controller/RoomController.java
  src/main/java/com/douzone/server/dto/department/DepartmentResDTO.java
  src/main/java/com/douzone/server/dto/employee/EmpResDTO.java
  src/main/java/com/douzone/server/dto/employee/ProfileDto.java
  src/main/java/com/douzone/server/dto/employee/SignupReqDTO.java
  src/main/java/com/douzone/server/dto/position/PositionResDTO.java
  src/main/java/com/douzone/server/dto/reservation/MyReservationResDTO.java
  src/main/java/com/douzone/server/dto/reservation/ReservationResDTO.java
  src/main/java/com/douzone/server/dto/reservation/RoomWeekReservationCountDTO.java
  src/main/java/com/douzone/server/dto/reservation/SoonAndIngResDTO.java
  src/main/java/com/douzone/server/dto/room/RoomResDTO.java
  src/main/java/com/douzone/server/dto/team/TeamResDTO.java
  src/main/java/com/douzone/server/entity/ReservationAttend.java
  src/main/java/com/douzone/server/entity/RoomReservation.java
  src/main/java/com/douzone/server/entity/Team.java
  src/main/java/com/douzone/server/repository/RoomRepository.java
  src/main/java/com/douzone/server/repository/RoomReservationRepository.java
  src/main/java/com/douzone/server/repository/querydsl/RoomQueryDSL.java
  src/main/java/com/douzone/server/repository/querydsl/RoomReservationQueryDSL.java
  src/main/java/com/douzone/server/service/RoomService.java
  src/main/java/com/douzone/server/test/Test.java
Labels: 🙂 FEAT

#21 feat: 차량 예약 수정 및 삭제 #19
  build.gradle
  src/main/java/com/douzone/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/douzone/server/config/security/filter/JwtTokenAuthorizationFilter.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationFilter.java
  src/main/java/com/douzone/server/config/security/handler/UserLogoutSuccessHandler.java
  src/main/java/com/douzone/server/config/security/interceptor/RoleInterceptor.java
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/config/utils/ResponseDTO.java
  src/main/java/com/douzone/server/controller/AdminController.java
  src/main/java/com/douzone/server/controller/EmployeeController.java
  src/main/java/com/douzone/server/controller/VehicleController.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleDateResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleEmpResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleListResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleRankResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleDateResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleEmpResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleListResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleRankResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleReqDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleReservationDTO.java
  src/main/java/com/douzone/server/entity/VehicleReservation.java
  src/main/java/com/douzone/server/repository/VehicleBookmarkRepository.java
  src/main/java/com/douzone/server/repository/VehicleRepository.java
  src/main/java/com/douzone/server/repository/VehicleReservationRepository.java
  src/main/java/com/douzone/server/repository/querydsl/EmployeeQueryDSL.java
  src/main/java/com/douzone/server/service/AdminService.java
  src/main/java/com/douzone/server/service/EmployeeService.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🙂 FEAT

#65 내예약현황, 예약 전체 현황 페이징
  src/main/java/com/douzone/server/config/utils/ErrorResponseDTO.java
  src/main/java/com/douzone/server/controller/RoomController.java
  src/main/java/com/douzone/server/dto/reservation/RegistReservationReqDto.java
  src/main/java/com/douzone/server/dto/reservation/ReservationPagingRes.java
  src/main/java/com/douzone/server/dto/room/RoomReservationSearchDTO.java
  src/main/java/com/douzone/server/repository/querydsl/RoomQueryDSL.java
  src/main/java/com/douzone/server/service/RoomService.java
  src/main/java/com/douzone/server/service/method/ServiceMethod.java
  src/main/resources/application.properties
Labels: 🙂 FEAT

#67 feat: 차량 다중 조건 동적 조회
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/controller/VehicleController.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleVariousDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleSearchDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleVariousDTO.java
  src/main/java/com/douzone/server/repository/VehicleBookmarkRepository.java
  src/main/java/com/douzone/server/repository/VehicleRepository.java
  src/main/java/com/douzone/server/repository/VehicleReservationRepository.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🙂 FEAT

#69 fix: 변수 조건에 따른 차량 현황 조회 jpql -> querydsl 변경
  src/main/java/com/douzone/server/config/security/interceptor/RoleInterceptor.java
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/dto/vehicle/IVehicleVariousDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleSearchDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleVariousDTO.java
  src/main/java/com/douzone/server/repository/VehicleImgRepository.java
  src/main/java/com/douzone/server/repository/VehicleRepository.java
  src/main/java/com/douzone/server/repository/VehicleReservationRepository.java
  src/main/java/com/douzone/server/repository/querydsl/VehicleQueryDSL.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🔨 FIX, ✂ REFAC

#64 test : websocket github 예제 보면서 실습, 전략 구상 등
  src/main/java/com/douzone/server/config/socket/Calendar.java
  src/main/java/com/douzone/server/config/socket/TestCalendarController.java
  src/main/java/com/douzone/server/config/socket/TestCalendarRepository.java
  src/main/java/com/douzone/server/config/socket/TestCalendarRoom.java
  src/main/java/com/douzone/server/config/socket/TestMessage.java
  src/main/java/com/douzone/server/config/socket/TestTimeMessage.java
  src/main/java/com/douzone/server/config/socket/TimeService.java
  src/main/java/com/douzone/server/config/socket/WebSocketConfig.java
  src/main/java/com/douzone/server/config/socket/WebSocketTestHandler.java
  src/main/java/com/douzone/server/config/utils/Msg.java
Labels: 🙂 FEAT, 📜 TEST

#74 Feat : 차량 중복 예약 방지 완료
  src/main/java/com/douzone/server/config/s3/AwsS3.java
  src/main/java/com/douzone/server/config/security/interceptor/InterceptorConfig.java
  src/main/java/com/douzone/server/config/socket/Calendar.java
  src/main/java/com/douzone/server/config/socket/CalendarRepository.java
  src/main/java/com/douzone/server/config/socket/CalendarRoomDTO.java
  src/main/java/com/douzone/server/config/socket/CalendarService.java
  src/main/java/com/douzone/server/config/socket/SocketResDTO.java
  src/main/java/com/douzone/server/config/socket/Time.java
  src/main/java/com/douzone/server/config/socket/TimeMessageReqDTO.java
  src/main/java/com/douzone/server/config/socket/TimeMessageResDTO.java
  src/main/java/com/douzone/server/config/socket/TimeRepository.java
  src/main/java/com/douzone/server/config/socket/TimeService.java
  src/main/java/com/douzone/server/config/socket/WebSocketHandler.java
  src/main/java/com/douzone/server/config/socket/vehicle/TimeVehicle.java
  src/main/java/com/douzone/server/config/socket/vehicle/TimeVehicleRepository.java
  src/main/java/com/douzone/server/config/socket/vehicle/VehicleRoomDTO.java
  src/main/java/com/douzone/server/config/socket/vehicle/VehicleSocketDTO.java
  src/main/java/com/douzone/server/config/socket/vehicle/VehicleSocketResDTO.java
  src/main/java/com/douzone/server/config/socket/vehicle/VehicleSocketService.java
  src/main/java/com/douzone/server/config/utils/Message.java
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/config/utils/UploadDTO.java
  src/main/java/com/douzone/server/controller/AdminController.java
  src/main/java/com/douzone/server/controller/RoomController.java
  src/main/java/com/douzone/server/dto/admin/AdminTestDTO.java
  src/main/java/com/douzone/server/dto/employee/SignModReqDTO.java
  src/main/java/com/douzone/server/entity/Employee.java
  src/main/java/com/douzone/server/entity/RoomImg.java
  src/main/java/com/douzone/server/entity/RoomReservation.java
  src/main/java/com/douzone/server/exception/GlobalExceptionHandler.java
  src/main/java/com/douzone/server/service/AdminService.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🙂 FEAT

#84 fix: 차량 수정 확인 및 테스트
  src/main/java/com/douzone/server/config/utils/ResponseDTO.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🔨 FIX, 📜 TEST

#85 fix: 차량 사진 업로드 방식 수정
  src/main/java/com/douzone/server/dto/vehicle/VehicleImgDTO.java
  src/main/java/com/douzone/server/repository/VehicleImgRepository.java
  src/main/java/com/douzone/server/service/AdminService.java
Labels: 🔨 FIX, ✂ REFAC, 📜 TEST

#88 fix: 내 차량 조회 페이지네이션 처리 수정 #87
  src/main/java/com/douzone/server/repository/VehicleRepository.java
Labels: 🔨 FIX, 📜 TEST

#90 fix: 차량 컨트롤러 변경 및 토큰 발급 관리 수정
  deploy/deploy.sh
  src/main/java/com/douzone/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/douzone/server/config/security/filter/JwtTokenAuthorizationFilter.java
  src/main/java/com/douzone/server/config/security/interceptor/RoleInterceptor.java
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/controller/AdminController.java
  src/main/java/com/douzone/server/controller/RoomController.java
  src/main/java/com/douzone/server/controller/TokenController.java
  src/main/java/com/douzone/server/controller/VehicleController.java
  src/main/java/com/douzone/server/service/RoomService.java
  src/main/java/com/douzone/server/service/VehicleService.java
  src/test/java/com/douzone/server/InputDummyTest.java
  src/test/java/com/douzone/server/controller/testControllerTest.java
  src/test/java/com/douzone/server/repository/querydsl/EmployeeQueryDSLTest.java
  src/test/java/com/douzone/server/repository/querydsl/RoomQueryDSLTest.java
  src/test/java/com/douzone/server/service/AdminServiceTest.java
Labels: 🔨 FIX, ✂ REFAC, 📜 TEST

#93 fix: 내 차량 예약 현황 조회 수정 및 차량 이미지 조회 리턴 리스트로 수정
  src/main/java/com/douzone/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/douzone/server/config/security/filter/UserAuthenticationFilter.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleImgDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehiclePagingResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehiclePagingResDTO.java
  src/main/java/com/douzone/server/exception/ErrorCode.java
  src/main/java/com/douzone/server/exception/TokenSetNotFoundException.java
  src/main/java/com/douzone/server/repository/VehicleRepository.java
  src/main/java/com/douzone/server/service/AdminService.java
  src/main/java/com/douzone/server/service/VehicleService.java
Labels: 🔨 FIX

#96 Refactor: 차량 이미지 단일 조회 수정 및 리팩토링
  src/main/java/com/douzone/server/config/socket/vehicle/TimeVehicleRepository.java
  src/main/java/com/douzone/server/config/socket/vehicle/VehicleSocketService.java
  src/main/java/com/douzone/server/config/utils/ResponseDTO.java
  src/main/java/com/douzone/server/dto/vehicle/MyVehicleReservationDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleBookMarkDTO.java
  src/main/java/com/douzone/server/dto/vehicle/VehicleVariousDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleDateResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleEmpResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleListResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehiclePagingResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleWeekDTO.java
  src/main/java/com/douzone/server/dto/vehicle/impl/VehicleWeekTimeDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleDateResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleEmpResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleListResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleResDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleWeekDTO.java
  src/main/java/com/douzone/server/dto/vehicle/jpainterface/IVehicleWeekTimeDTO.java
  src/main/java/com/douzone/server/repository/VehicleRepository.java
  src/main/java/com/douzone/server/repository/querydsl/VehicleQueryDSL.java
  src/main/java/com/douzone/server/service/AdminService.java
  src/main/java/com/douzone/server/service/EmployeeService.java
  src/main/java/com/douzone/server/service/RoomService.java
  src/main/java/com/douzone/server/service/VehicleService.java
  src/main/java/com/douzone/server/service/method/RoomServiceMethod.java
  src/main/java/com/douzone/server/service/method/VehicleServiceMethod.java
Labels: 🔨 FIX, ✂ REFAC

#97 fix: 리프레쉬 토큰 발급 과정 수정
  src/main/java/com/douzone/server/config/security/filter/JwtTokenAuthorizationFilter.java
  src/main/java/com/douzone/server/config/utils/Msg.java
  src/main/java/com/douzone/server/service/VehicleService.java
  src/main/java/com/douzone/server/service/method/VehicleServiceMethod.java
Labels: 🔨 FIX
